Integration of Faro
redhat-performance/tooling-curator pull request #36
Opened 2023-08-09 17:38 UTC by shashank-boyapally

# Description
Faro is GPT chat-bot which will be integrated into tooling curator. It answers all your queries regarding the tools being used across PerfScale organizations.

It sends the query to faro backend and gets a response which is displayed as the chatbot response.

<img width="409" alt="Screenshot 2023-08-07 at 12 16 17 AM" src="https://github.com/redhat-performance/tooling-curator/assets/135713015/03ef8abe-a9a7-4a9b-8b69-6de189dea071">

2023-08-09 17:47 UTC, shashank-boyapally commented
request for review @chentex @dustinblack @smalleni

2023-08-10 10:28 UTC, dustinblack requested changes
Great stuff @shashank-boyapally! There are a few git hygiene items and other small things to consider.

- It isn't a show-stopper, more of a nit, but in general I'd prefer to see syntax and linting changes handled in a separate commit so that it's easier to review the functional and syntax changes separately.
- It looks like you inadvertently added the `scrape repos.py` file in the first commit and removed it later. It would be better to re-order those commits and squash the removal of that file into the initial commit instead of having a separate commit to remove the file. Again, a bit of a nit. As an aside, maybe avoid filenames with spaces in them. ;)
- I also think we need to mark this as "Experimental" somehow in the UI in order to set appropriate expectations, maybe also with some "how to provide feedback" instructions.
- The corporate side of me would complain about the outdated Shadowman branding, but the old school rebellious Red Hatter in me loves it and wants it to stay for now.

2023-08-10 13:35 UTC, shashank-boyapally commented
Thank you for the feedback @dustinblack. I'll be making those changes. The linting was done by an extension and it wasn't an intentional one. I'll roll back to our previous code and make a separate commit for linting. I'll also squash those commits before pushing them.
For experimental feature, how about we add "(experimental)" on the top bar of the chatbot, we can also provide an icon on the top right and when the user hover's over it, he/she get's the instructions to provide feedback. Please let me know if this sounds good. Any other changes are also welcome. I too love the shadowman, we can have it until we have a new mascot for our bot.

2024-04-17 13:23 UTC, dustinblack approved these changes

2024-04-17 13:23 UTC, merged